name: covid_vaccine
description: 안전 백신 정보 Plus - 예방접종 정보
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.4

  google_mobile_ads: ^0.13.0

  intl:
  freezed_annotation:

  font_awesome_flutter: ^9.0.0

  search_choices: ^2.0.3

  flutter_local_notifications: ^6.0.0
  package_info: ^2.0.1
  url_launcher: ^6.0.3
  share: ^2.0.2
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sido/

  fonts:
    - family: BMJUA
      fonts:
        - asset: fonts/BMJUA_ttf.ttf
    - family: GmarketSansBold
      fonts:
        - asset: fonts/GmarketSansTTFBold.ttf
